language: node_js
node_js:
  - '8.9.1'
sudo: required
dist: trusty
branches:
  only:
    - master

addons:
  chrome: stable

before_install:
  - # start your web application and listen on `localhost`
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &

# before_install:
# - |
#   export DISPLAY=:99.0
#   sh -e /etc/init.d/xvfb start
#   sudo apt-key adv --fetch-keys http://dl.yarnpkg.com/debian/pubkey.gpg
#   echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
#   sudo apt-get update -qq
#   sudo apt-get install -y -qq yarn
#   yarn --version
#   # install the most recent `npm version`
#   # used when publishing to build a properly packed tarball
#   npm i -g npm
# install:
# - |
#   yarn install

before_script:
  - npm install -g firebase-tools
  - npm install -g @angular/cli

script:
  # output useful info for debugging
  - node --version
  - npm --version
  # run tests
  - npm run test.ci
  - npm run build

after_success:
  - firebase deploy --token $FIREBASE_TOKEN

# notifications:
#   email:
#     on_failure: guanghui-wang@foxmail.com
#     on_success: guanghui-wang@foxmail.com
